version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  user:
    container_name: user
    build:
      context: .
      dockerfile: ./docker/user/Dockerfile
    command: ["npm", "--prefix", "packages/user","run", "prod"]
    environment:
      - PORT=4000
      - POSTGRES_DB=glassbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - kafka
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./packages/user:/glassbox-ms/packages/user

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    command: ["npm", "--prefix", "packages/worker", "run", "prod"]
    environment:
      - PORT=5000
      - POSTGRES_DB=glassbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=secret
    depends_on:
      - kafka
    ports:
      - "5000:5000"
    volumes:
      - ./packages/worker:/glassbox-ms/packages/worker

  fastify-web:
    container_name: fastify-web
    build:
      context: .
      dockerfile: ./docker/fastify-web/Dockerfile
    command: ["npm", "--prefix", "packages/fastify-web", "run", "prod"]
    environment:
      - PORT=6000
    depends_on:
      - kafka
    ports:
      - "6000:6000"
    volumes:
      - ./packages/worker:/glassbox-ms/packages/fastify-web
  
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: glassbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

